'{"fruit": "Apple", "color": "red", "shape": "sphere"}',
'{"fruit": "banana", "color": "yellow", "shape": "elongated"}',
'{"fruit": "pear:, "color": "green", "shape": "pear shaped"}',
'{"fruit": "orange", "color": "orange", "shape": "sphere"}',
'{"fruit": "grapes", "color": "purple", "shape": "sphere"}',
